### ISSUE TITLE
Finder Mount

### ISSUE THREAD

**Issue by roizcorp** [ganeshrvel/openmtp#343]
I am syncing songs to my Garmin watch, I am managing it via shell script (rsync and what not). I cannot seem to fnd where OpenMTP mounts the watch on the filesystem so I could point the script to the proper folder.

So I assume OpenMTP does not mounts on the filesystem (which I cannot explain how this is even possible) but if so, can you add this support?

**Comment by vokain** [comment]
I support this!

**Comment by ganeshrvel** [comment]
Currently, OpenMTP doesn't mount devices in the filesystem in the traditional sense, which is why you're not seeing the Garmin watch appear as a regular folder. However, I'm planning a complete rewrite of OpenMTP, and I will consider including support for filesystem mounting in future releases. This should help integrate better with scripts like yours. Stay tuned!

**Comment by roizcorp** [comment]
Thank you very much, good luck
